@url_dev= http://127.0.0.1:3053/v1/api/
### signup
POST {{url_dev}}shop/signup
Content-Type: application/json

{
    "name": "Shop laptop",
    "email": "thanhchonthanh@gmail.com",
    "password": "123456"
}